protocol_mapping:
  ATAC: pepatac.py
  ATAC-SEQ: pepatac.py 
  ATAC-seq: pepatac.py 

pipelines:
  pepatac.py:
    name: PEPATAC
    path: pipelines/pepatac.py
    looper_args: True
    required_input_files: [read1]
    all_input_files: [read1, read2]
    ngs_input_files: [read1, read2]
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": read1
      "--single-or-paired": read_type
    optional_arguments:
      "--input2": read2
      "--peak-caller": peak_caller
      "--frip-ref-peaks": FRIP_ref
      "--prealignments": prealignments
      "--deduplicator": deduplicator
      "--trimmer": trimmer
      "--genome-size": macs_genome_size
      "--anno-name": anno_name
      "--TSS-name": TSS_name
      "--keep": keep
      "--noFIFO": no_fifo
      "--lite": lite
    outputs:
      smooth_bw: "aligned_{sample.genome}/{sample.sample_name}_smooth.bw"
      exact_bw:  "aligned_{sample.genome}_exact/{sample.sample_name}_exact.bw"
      aligned_bam: "aligned_{sample.genome}/{sample.sample_name}_sort.bam"
      # pre_smooth_bw: "aligned_{project.prealignments}/{sample.sample_name}_smooth.bw"
      peaks_bed: "peak_calling_{sample.genome}/{sample.sample_name}_peaks.bed"
      summits_bed: "peak_calling_{sample.genome}/{sample.sample_name}_summits.bed"
    compute:
      singularity_image: ${SIMAGES}pepatac
      docker_image: databio/pepatac
    summarizers:
      - tools/PEPATAC_summarizer.R
    bioconductor:
      readFunName: readPepatacPeakBeds
      readFunPath: BiocProject/readPepatacPeakBeds.R
    summary_results:
      - alignment_percent_file:
        caption: "Alignment percent file"
        description: "Plots percent of total alignment to all pre-alignments and primary genome."
        thumbnail_path: "summary/{name}_alignmentPercent.png"
        path: "summary/{name}_alignmentPercent.pdf"
      - alignment_raw_file:
        caption: "Alignment raw file"
        description: "Plots raw alignment rates to all pre-alignments and primary genome."
        thumbnail_path: "summary/{name}_alignmentRaw.png"
        path: "summary/{name}_alignmentRaw.pdf"
      - tss_file:
        caption: "TSS enrichment file"
        description: "Plots TSS scores for each sample."
        thumbnail_path: "summary/{name}_TSSEnrichment.png"
        path: "summary/{name}_TSSEnrichment.pdf"
    resources:
      default:
        file_size: "0"
        cores: "8"
        mem: "16000"
        time: "00-18:00:00"
      femto:
        file_size: "0.001"
        cores: "1"
        mem: "8000"
        time: "00-04:00:00"
      pico:
        file_size: "0.05"
        cores: "2"
        mem: "12000"
        time: "00-08:00:00"
      nano:
        file_size: "0.5"
        cores: "4"
        mem: "16000"
        time: "00-12:00:00"
      micro:
        file_size: "1"
        cores: "8"
        mem: "16000"
        time: "00-24:00:00"
      milli:
        file_size: "10"
        cores: "16"
        mem: "32000"
        time: "02-00:00:00"

