protocol_mapping:
  ATAC: pepatac.py
  ATAC-SEQ: pepatac.py 

pipelines:
  pepatac.py:
    name: PEPATAC
    path: pipelines/pepatac.py
    looper_args: True
    required_input_files: [read1]
    all_input_files: [read1, read2]
    ngs_input_files: [read1, read2]
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": read1
      "--single-or-paired": read_type
    optional_arguments:
      "--input2": read2
      "--peak-caller": peak_caller
      "--frip-ref-peaks": FRIP_ref
      "--prealignments": prealignments
      "--genome-size": macs_genome_size
      "--anno-name": anno_name
      "--TSS-name": TSS_name
      "--keep": keep
      "--noFIFO": no_fifo
    compute:
      singularity_image: ${SIMAGES}pepatac
      docker_image: databio/pepatac
    summarizers:
      - tools/PEPATAC_summarizer.R
    summary_results:
      - alignment_percent_file:
        caption: "Alignment percent file"
        description: "Plots percent of total alignment to all pre-alignments and primary genome."
        thumbnail_path: "summary/{name}_alignmentPercent.png"
        path: "summary/{name}_alignmentPercent.pdf"
      - alignment_raw_file:
        caption: "Alignment raw file"
        description: "Plots raw alignment rates to all pre-alignments and primary genome."
        thumbnail_path: "summary/{name}_alignmentRaw.png"
        path: "summary/{name}_alignmentRaw.pdf"
      - tss_file:
        caption: "TSS enrichment file"
        description: "Plots TSS scores for each sample."
        thumbnail_path: "summary/{name}_TSSEnrichment.png"
        path: "summary/{name}_TSSEnrichment.pdf"
    resources:
      default:
        file_size: "0"
        cores: "8"
        mem: "16000"
        time: "0-04:00:00"


