# This project config file describes your project. See looper docs for details.
name: BiocProject # The name that summary files will be prefaced with

pep_version: 2.0.0
sample_table: gold_sample_table.csv  # sheet listing all samples in the project

looper:  # relative paths are relative to this config file
  output_dir: "$PROCESSED/pepatac/gold"  # ABSOLUTE PATH to the parent, shared space where project results go
  pipeline_interfaces: ["$CODE/pepatac/project_pipeline_interface.yaml"]  # ABSOLUTE PATH to the directory where looper will find the pipeline repository

sample_modifiers:
  append:
    pipeline_interfaces: ["$CODE/pepatac/sample_pipeline_interface.yaml"]
  derive:
    attributes: [read1, read2]
    sources:
      SRA_1: "${SRAFQ}{SRR}_1.fastq.gz"
      SRA_2: "${SRAFQ}{SRR}_2.fastq.gz"
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38
        macs_genome_size: hs
        prealignments: rCRSd
        aligner: bowtie2         # Default. [options: bwa]
        deduplicator: samblaster # Default. [options: picard]
        trimmer: skewer          # Default. [options: pyadapt, trimmomatic]
        peak_caller: macs2       # Default. [options: fseq, genrich, hmmratac, homer]
        peak_type: fixed         # Default. [options: variable]
        extend: "250"            # Default. For fixed-width peaks, extend this distance up- and down-stream.
        frip_ref_peaks: None     # Default. Use an external reference set of peaks instead of the peaks called from this run
        blacklist: $GENOMES/hg38/blacklist/default/hg38_blacklist.bed.gz

bioconductor:
  readFunName: readNarrowPeak
  readFunPath: readNarrowPeak.R
  funcArgs:
    output_dir: "$PROCESSED/pepatac/gold" 
    results_subdir: "$PROCESSED/pepatac/gold/results_pipeline/" 