pep_config: tutorial_refgenie_pep_config.yaml # if you would like to run without using refgenie, point this to tutorial_pep_config.yaml

output_dir: "${TUTORIAL}/processed/"
pipeline_interfaces:
  - "${TUTORIAL}/tools/pepatac/sample_pipeline_interface.yaml"
  - "${TUTORIAL}/tools/pepatac/project_pipeline_interface.yaml"

pipestat:
  results_file_path: "${TUTORIAL}/processed/results_pipeline/{record_identifier}/stats.yaml"
