# This pep config file describes your project. See looper docs for details.
name: test_project # The name that summary files will be prefaced with
pep_version: 2.1.0
sample_table: test_annotation.csv  # sheet listing all samples in the project

sample_modifiers:
  derive:
    attributes: [read1, read2]
    sources:
      test_data_R1: "examples/data/{sample_name}_r1.fastq.gz"
      test_data_R2: "examples/data/{sample_name}_r2.fastq.gz"
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38
        genome_index: default/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4
        chrom_sizes: default/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
        prealignment_index: ["rCRSd=default/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4"]
