pep_config: gold_pep_config.yaml # if you would like to run using refgenie, point this to gold_pep_config_refgenie.yaml

output_dir: "${PROCESSED}/pepatac/gold_atac/default"
pipeline_interfaces:
  - "${CODE}/pepatac/sample_pipeline_interface.yaml"
  - "${CODE}/pepatac/project_pipeline_interface.yaml"

pipestat:
  results_file_path: "${PROCESSED}/results_pipeline/{record_identifier}/stats.yaml"
